### PR TITLE
Create isAdmin bool value from cookie to avoid bug

### LINKED ISSUE #22: marketplace edit and delete function should be limit to author or admin

### LINKED ISSUE #23: the admin in cookie is string instead of bool

### PR DESCRIPTION
**Pull request by debuggy**
closes #23 
closes #22

### CODE REVIEW

File: webportal_plugin/src/app/market_detail/components/summary.jsx [hunk 1]
```diff
@@ -88,6 +91,8 @@ export default function Summary(props) {
     );
   };
 
+  console.log(checkAuthorAdmin());
```
Comment (hzy46) [inline webportal_plugin/src/app/market_detail/components/summary.jsx:94]: Remove this?

Comment (debuggy) [reply webportal_plugin/src/app/market_detail/components/summary.jsx]: done
